name: CI

on:
  push:
    branches: [ "**" ]
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check current branch restrictions
        id: allow_step
        run: echo "::set-output name=allow-step::$([[ "$(grep -icm1 '${{ github.ref }}' .github/workflows/.build-branch-allow)" = 1 ]] && echo ALLOW || echo NOT_ALLOW)"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install build, wheel
        run: |
          python -m pip install build --user
          python -m pip install -Iv wheel==0.36.2 --user

      - name: Define NSG Version
        id: nsg_version
        uses: happygears/gt2v@v4

      - name: Print NSG Version
        run: |
          echo "Build version :point_down:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.nsg_version.outputs.long_version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Set version
        shell: bash
        run: echo "__version__ = '${{ steps.nsg_version.outputs.long_version }}'" > nsgcli/version.py

      #python -m build --sdist --wheel --outdir dist/
      - name: Build
        shell: bash
        run: python setup.py sdist bdist_wheel

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
