name: CI

on:
  push:
    branches: [ "**" ]
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current branch restrictions
        id: allow_step
        run: echo "::set-output name=allow-step::$([[ "$(grep -icm1 '${{ github.ref }}' .github/workflows/.build-branch-allow)" = 1 ]] && echo ALLOW || echo NOT_ALLOW)"

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      #python setup.py sdist bdist_wheel
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/
